# GA6 - Matrix Methods
### M. Molter

This looks to be the last Guided Activity of the ME273 semester. While MATLAB was specifically designed for performing matrix operations, I think the modern [`numpy`](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) python libraries will give MATLAB a run for its (very large sum of) money. Numpy is a [wraper](https://docs.scipy.org/doc/numpy-1.10.0/user/c-info.python-as-glue.html) for down-to-the-metal `FORTRAN` and `C` methods.

Further, Jupyter Notebook has a number of built-in [`magic`](http://ipython.readthedocs.io/en/stable/interactive/magics.html) methods to help with code timing. Today we will be working with `%timeit` and `%%timeit` (the multi-line cousin). These decorators will run the line of code 3 to 1000 times (depending on computational intensity) and report the mean, worst, and best-case runtimes.

While we are here, lets get the required libraries imported.

In [1]:
import numpy as np

## Exercise 1 
### Gause Elimination

Consider the following system of linear equations.

$$27.6x_1 - 123.5x_2 - 97.8x_3 = -11$$
$$45.5x_1 + 100.3x_2 + 2.1x_3 = 744.3$$
$$1.2x_1 + 67.3x_2 + 99.4x_3 = 7.7$$

Solve the systems for $x_1$, $x_2$, and $x_3$ using **Gaus elimination**. You will, unfortunetly, have to write the solution out by hand (with the aid of a calculator!); but, the good news: this is the only assignment in ME273 this semester that requires a good 'ol fashioned pencil and paper (ha...) effor! Since Hon. Prof. wants you to submit a .pdf of your GA report, can you create a digital copy of your solution for this exercises and include it in your single pdf?

#### Solution

The first step is to put this system of equations in matrix form:

$$
\begin{bmatrix}
    27.6  &  -123.5  &  -97.8  \\
    45.5  &   100.3  &    2.1  \\
     1.2  &    67.3  &   99.4  \\
\end{bmatrix}
\begin{bmatrix}
    x_1  \\
    x_2  \\
    x_3  \\
\end{bmatrix}
=
\begin{bmatrix}
    -11 \\
    744.3 \\
    7.7 \\
\end{bmatrix}
$$

We can now add rows to one another, and multiply rows by constants. The goal is to get a matrix $A$ of the form:

$$
\begin{bmatrix}
    1 & A & B \\
    0 & 1 & C \\
    0 & 0 & 1 \\
\end{bmatrix}
$$

Now we start manipulating the matrix.

$$\frac{1}{27.6}R_1 \rightarrow R_1$$
$$\frac{1}{45.5}R_2 \rightarrow R_2$$
$$\frac{1}{1.2}R_3 \rightarrow R_3$$

$$
\begin{bmatrix}
     1  &    -4.47464   &   -3.54348   \\
     1  &     2.204396  &    0.046154  \\
     1  &    56.083333  &   82.833333  \\
\end{bmatrix}
\begin{bmatrix}
    x_1  \\
    x_2  \\
    x_3  \\
\end{bmatrix}
=
\begin{bmatrix}
    -0.39855 \\
    16.35824 \\
     6.41667 \\
\end{bmatrix}
$$

$$R_2 - R_1 \rightarrow R_2$$
$$R_3 - R_1 \rightarrow R_3$$

$$
\begin{bmatrix}
     1  &    -4.47464   &   -3.54348   \\
     0  &     6.679033  &    3.589632  \\
     0  &    60.55797   &   86.37681  \\
\end{bmatrix}
\begin{bmatrix}
    x_1  \\
    x_2  \\
    x_3  \\
\end{bmatrix}
=
\begin{bmatrix}
    -0.39855 \\
    16.75679 \\
     6.815217 \\
\end{bmatrix}
$$

$$\frac{1}{6.679033}R_2 \rightarrow R_2$$
$$\frac{1}{60.55797}R_3 \rightarrow R_3$$

$$
\begin{bmatrix}
     1  &    -4.47464   &   -3.54348   \\
     0  &     1         &    0.537448  \\
     0  &     1         &    1.426349  \\
\end{bmatrix}
\begin{bmatrix}
    x_1  \\
    x_2  \\
    x_3  \\
\end{bmatrix}
=
\begin{bmatrix}
    -0.39855  \\
     2.508865 \\
     0.112540 \\
\end{bmatrix}
$$

$$R_3 - R_2 \rightarrow R_3$$

$$
\begin{bmatrix}
     1  &    -4.47464   &   -3.54348   \\
     0  &     1         &    0.537448  \\
     0  &     0         &    0.888901  \\
\end{bmatrix}
\begin{bmatrix}
    x_1  \\
    x_2  \\
    x_3  \\
\end{bmatrix}
=
\begin{bmatrix}
    -0.39855  \\
     2.508865 \\
    -2.39632 \\
\end{bmatrix}
$$

$$\frac{1}{0.888901}R_3 \rightarrow R_3$$

$$
\begin{bmatrix}
     1  &    -4.47464   &   -3.54348   \\
     0  &     1         &    0.537448  \\
     0  &     0         &    1         \\
\end{bmatrix}
\begin{bmatrix}
    x_1  \\
    x_2  \\
    x_3  \\
\end{bmatrix}
=
\begin{bmatrix}
    -0.39855  \\
     2.508865 \\
    -2.69583 \\
\end{bmatrix}
$$

Now that we have the matrix in the proper form, we revert to simple substitution to find the solutions.

$$x_3 = -2.69583$$

$$x_2 + 0.537448 x_3 = 2.508865$$
$$x_2 = 2.508865 - 0.537448 x_3 = 2.508865 - 0.537448 (-2.69583) = 3.957733$$

$$x_1 - 4.47464 x_2 - 3.54348 x_3 = -0.39855$$
$$x_1 = -0.39855 + 4.47464 x_2 + 3.54348 x_3 = -0.39855 + 4.47464 (3.95773) + 3.54348 (-2.69583) = 7..758247$$

Substiting these back into $x$, we get:

$$x = \begin{bmatrix} 7.758247 \\ 3.957733 \\ -2.69583 \end{bmatrix}$$

The correct answer (as verified by the later exercises).

## Exercise 2
### Cramer's Rule

Express the system of equations in the form

$$\vec{A} \vec{x} = \vec{b}$$

Solve the system of equations above using Cramer's Rule. Write the solution as a script and describe the output in your report.

### Solution

First up, lets get the matricies into Python.

In [10]:
A = np.asarray([[27.6, -123.5, -97.8],
                [45.5,  100.3,   2.1],
                [ 1.2,   67.3,  99.4]])

b = np.asarray([[-11.0],
                [744.3],
                [  7.7]])

[**Cramer's rule**](https://en.wikipedia.org/wiki/Cramer%27s_rule) is an algorithm that can determine the solution to individual $x_i$ variables. 

It takes a matrix equation fo the form:

$$\vec{A} \vec{x} = \vec{b}$$

An returns indiviual solutions accroding to:

$$x_i = \frac{\det(A_i)}{\det(A)}$$

Where $A_i$ is $A$ with the i-th column replaced by the column vector $b$.

In [11]:
def cramer(A, b):
    ''' Return x for sytem Ax = b using Cramer's rule. '''
    
    # Grab the determinant of A.
    det_A = np.linalg.det(A)

    # Count columns in A.
    columns = A.shape[1]

    # Create result array of size `columns`.
    x = np.empty((columns, 1))

    # Perform Cramer rule on each element of solution array.
    for i in range(columns):

        # Deep copy (i.e. no referencing) A into A_i.
        A_i = np.copy(A)

        # Replace column i of A_i with vector b.
        A_i[:, i] = b.reshape(columns)

        # Get the deteminant of A_i.
        det_A_i = np.linalg.det(A_i)

        # Calculate the result element x_i and put it in x.
        x_i = det_A_i / det_A
        x[i] = x_i
        
    return x

x = cramer(A, b)
%timeit x = cramer(A, b)
print(x)

49.1 µs ± 4.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[[ 7.75825837]
 [ 3.95773162]
 [-2.69582745]]


## Excersice 3
### Inverse of A

Use the inverse of $\vec{A}$ to calculate the solution vector, $\vec{x}$, for the system of equations. Include this inverse calculation in the same script you created for Exercise 2.

#### Solution 

The numpy code here is pretty much explains itself. We are essentially performing the following operation:

$$\vec{A} \vec{x} = \vec{b}$$
$$(\vec{A})^{-1}\vec{A} \vec{x} = \vec{I} \vec{x} =  (\vec{A})^{-1}\vec{b}=\vec{x}$$



In [12]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.01814039,  0.01050931,  0.01762636],
       [-0.00834287,  0.00528016, -0.00832013],
       [ 0.00542965, -0.00370187,  0.01548082]])

In [13]:
x = np.dot(A_inv, b)
x

array([[ 7.75825837],
       [ 3.95773162],
       [-2.69582745]])

In [14]:
def inverse_solve(A, b):
    ''' Return x for system Ax = b using inverse and dot method. '''
    
    return np.dot(np.linalg.inv(A), b)

%timeit x = inverse_solve(A, b)
x

23.1 µs ± 1.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


array([[ 7.75825837],
       [ 3.95773162],
       [-2.69582745]])

## Exercise 4
### Optimized MATLAB (Python) Solution

Calculate the solution vector via optimized MATLAB (Python) solution for a system of equations. Compre the results of each of these methods and comment appropriately. Incluce this cacluation in the same script you created for Exercises 2 and 3.

In [15]:
%timeit x = np.linalg.solve(A, b)
x

10 µs ± 703 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([[ 7.75825837],
       [ 3.95773162],
       [-2.69582745]])

## Exercise 5
### Large Matrix

Create a large matrix, $\vec{A}$, comprised of elements randomly generated from $\pm 100$, and a corresponding vector $\vec{b}$, whose elements are also randomly generated in the same range. Calculate the solution vector $\vec{x}$ for this system of equations via the matrix inverse method and the optimized MATLAB (Python) method, and compare the results. "Large" means a matrix sufficiently large to require at least a few minutes of run time. To make the comparison, define another matrix that calculates the difference between the two solution, and ouptut the minimum and macimum of this difference matrix. Comment on the result.

In [ ]:
n = int(10e3)

A = 200 * np.random.random_sample((n, n)) - 100
b = 200 * np.random.random_sample((n, 1)) - 100

%timeit x = np.linalg.solve(A, b)

Even when performing operations on an $10,000 \times 10,000$ matrix, the computation time only averages 22.8 (s). I'm not going to go much further than that because the mechanism for the slowdown is machine dependent, not algorithm dependent.

Numpy is ultrafast. That is...until your arrays become larger than the avaiable RAM. Then your operating system has to start stashing some of those RAM addresses on the drive--and those `cache misses` are extremely expensive in terms of wasted clock cycles. 

While a proces can hit the L1 cache in just a few cycles, hitting the RAM takes dozens of cycles. Hitting the drive can take miliseconds!

While I *could* push the limits, make the matricies larger, they would only slow down the operation my user-grade Surface Pro 4 (only has 4 GB RAM). If I pushed the operation onto our production server at work (64 GB RAM), even though the process is *slower* (through-put is different), the matrix operations would complete almost instantaneously.